# Generated by Django 4.2.16 on 2024-11-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicuota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
