# Generated by Django 4.2.16 on 2024-11-02 03:17

import alicuota.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicuota', '0002_residente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[alicuota.util.validar_cedula_ecuatoriana], verbose_name='Cédula'),
        ),
    ]
