# Generated by Django 4.2.16 on 2024-11-02 04:32

import alicuota.util
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicuota', '0003_alter_residente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[alicuota.util.validar_cedula_ecuatoriana, django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')], verbose_name='Teléfono'),
        ),
    ]
